stages:
  prepare_data:
    cmd: python src/Classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images

  prepare_base_model:
    cmd: python src/Classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES 
      - WEIGHTS 
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/Classifier/pipeline/stage_03_training.py
    deps:
      - src/Classifier/pipeline/stage_03_training.py
      - src/Classifier/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/trained_model.keras

  evaluation:
    cmd: python src/Classifier/pipeline/stage_04_evaluation.py
    deps:
      - src/Classifier/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training/trained_model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    outs:
      - scores.json :
          cache: false



# dvc init 
# dvc repro
