
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/mehraj-alom/DATA/raw/refs/heads/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/local_data.zip
  unzip_dir: artifacts/data_ingestion

prepared_base_model:
  root_dir: artifacts/prepared_base_model
  base_model_path: artifacts/prepared_base_model/base_model.h5
  updated_base_model_path: artifacts/prepared_base_model/updated_base_model.h5

prepare_callbacks:
  root_dir : artifacts/prepare_callbacks
  tensorboard_root_log_dir : artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_path: artifacts/prepare_callbacks/checkpoint_dir/checkpoint_model.keras

training:
  root_dir: artifacts/training 
  trained_model_path: artifacts/training/trained_model.keras
 